trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define the Azure service connection created earlier
  ARM_CLIENT_ID: $(servicePrincipalClientId)
  ARM_CLIENT_SECRET: $(servicePrincipalClientSecret)
  ARM_SUBSCRIPTION_ID: $(servicePrincipalSubscriptionId)
  ARM_TENANT_ID: $(servicePrincipalTenantId)

steps:
- task: TerraformCLI@1
  displayName: 'terraform init'
  inputs:
    command: init
    environmentServiceName: 'Terraform ARM'
    # Subscription id for provider to target. This can be used to specify the subscription when using Management Group scoped
    # Service connection or to override the subscription id defined in a Subscription scoped service connection
    providerAzureRmSubscriptionId: 'c56e8840-689a-46f8-aee9-85f838735de4'

- task: TerraformCLI@1
  displayName: 'terraform plan'
  inputs:
    command: plan
    environmentServiceName: 'Terraform ARM'
    # Subscription id for provider to target. This can be used to specify the subscription when using Management Group scoped
    # Service connection or to override the subscription id defined in a Subscription scoped service connection
    providerAzureRmSubscriptionId: 'c56e8840-689a-46f8-aee9-85f838735de4'